import React, { useState, useEffect } from 'react';
import { 
  Database, 
  Search, 
  Layers, 
  Sparkles, 
  Trash2, 
  Shuffle, 
  CheckCircle2, 
  BookOpen, 
  Clock, 
  Filter 
} from 'lucide-react';
import { GlassCard } from '../ui/GlassCard';
import { Question } from '../../types';
import { collection, onSnapshot, query, limit, doc, deleteDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';

export const AdminQuestionBank: React.FC = () => {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSubject, setSelectedSubject] = useState<string>('all');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    try {
      const q = query(collection(db, 'questions_bank'), limit(200));
      const unsub = onSnapshot(q, (snapshot) => {
        const list: Question[] = snapshot.docs.map((d) => ({
          id: d.id,
          ...d.data(),
        } as Question));
        setQuestions(list);
        setLoading(false);
      }, (err) => {
        console.warn('Questions bank read error:', err);
        setLoading(false);
      });

      return () => unsub();
    } catch (e) {
      setLoading(false);
    }
  }, []);

  const handleDelete = async (id: string) => {
    if (!confirm('Remove this question from the persistent question bank?')) return;
    try {
      await deleteDoc(doc(db, 'questions_bank', id));
    } catch (err: any) {
      alert('Error deleting question: ' + err.message);
    }
  };

  const filtered = questions.filter((q) => {
    const matchSearch = searchTerm === '' || 
      q.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
      q.topic?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      q.subjectId?.toLowerCase().includes(searchTerm.toLowerCase());

    const matchSubject = selectedSubject === 'all' || q.subjectId === selectedSubject;
    return matchSearch && matchSubject;
  });

  const uniqueSubjects = Array.from(new Set(questions.map((q) => q.subjectId).filter(Boolean)));

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-900/60 border border-slate-800">
        <div>
          <h2 className="text-lg font-bold text-slate-100 font-['Outfit'] flex items-center gap-2">
            <Database className="w-5 h-5 text-cyan-400" />
            <span>Persistent AI Question Bank & Fallback Pool</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Questions generated by Gemini 3.8 Flash automatically accumulate here. During AI rate limits, the system jumbles questions directly from this pool.
          </p>
        </div>

        <div className="px-3.5 py-1.5 rounded-xl bg-cyan-950/80 border border-cyan-500/40 text-xs font-bold text-cyan-300 flex items-center gap-2">
          <Shuffle className="w-3.5 h-3.5 text-cyan-400" />
          <span>{questions.length} Stored Questions</span>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row items-center gap-3">
        <div className="relative flex-1 w-full">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search questions by topic, formula, or concept..."
            className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs text-slate-100 focus:outline-none focus:border-cyan-500"
          />
        </div>

        <select
          value={selectedSubject}
          onChange={(e) => setSelectedSubject(e.target.value)}
          className="w-full sm:w-56 px-3.5 py-2.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
        >
          <option value="all">All Subjects ({questions.length})</option>
          {uniqueSubjects.map((sub) => (
            <option key={sub} value={sub}>{sub}</option>
          ))}
        </select>
      </div>

      {/* Questions List */}
      {loading ? (
        <div className="text-center py-12 text-xs text-slate-500">
          Loading question bank repository...
        </div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-12 rounded-2xl bg-slate-900/40 border border-slate-800 text-xs text-slate-400">
          No questions found matching your filter. Generate questions in the AI Study Lab or Battle Arena to populate this pool.
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((q, idx) => (
            <GlassCard key={q.id || idx} className="p-4 sm:p-5">
              <div className="flex items-start justify-between gap-3">
                <div className="space-y-1.5 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="px-2 py-0.5 rounded bg-cyan-950/80 border border-cyan-800 text-[10px] font-bold text-cyan-400">
                      {q.subjectId}
                    </span>
                    <span className="px-2 py-0.5 rounded bg-slate-800 text-[10px] text-slate-300">
                      Unit {q.unit}
                    </span>
                    <span className="text-[11px] text-slate-400 truncate max-w-xs">
                      {q.topic}
                    </span>
                    {q.isAiGenerated ? (
                      <span className="inline-flex items-center gap-1 text-[10px] text-violet-400">
                        <Sparkles className="w-2.5 h-2.5" /> AI Generated
                      </span>
                    ) : (
                      <span className="text-[10px] text-emerald-400">
                        Curriculum Seed
                      </span>
                    )}
                  </div>

                  <p className="text-xs sm:text-sm font-semibold text-slate-100 font-['Outfit'] pt-1">
                    {q.question}
                  </p>
                </div>

                <button
                  onClick={() => handleDelete(q.id)}
                  title="Remove from pool"
                  className="p-1.5 rounded-lg bg-slate-800/80 hover:bg-rose-500/20 text-slate-400 hover:text-rose-300 transition-colors flex-shrink-0"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Options */}
              {q.options && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3 pt-3 border-t border-slate-800/60">
                  {q.options.map((opt, optIdx) => {
                    const isCorrect = opt === q.correctAnswer;
                    return (
                      <div
                        key={optIdx}
                        className={`p-2 rounded-lg text-xs font-mono border ${
                          isCorrect 
                            ? 'bg-emerald-950/50 border-emerald-500/40 text-emerald-300 font-semibold' 
                            : 'bg-slate-900/60 border-slate-800/80 text-slate-200'
                        }`}
                      >
                        {opt}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* Explanation Toggle */}
              {q.explanation && (
                <div className="mt-3 pt-2 text-[11px] text-slate-400 bg-slate-900/50 p-2.5 rounded-lg border border-slate-800/60">
                  <span className="font-semibold text-cyan-400">Explanation: </span>
                  {q.explanation}
                </div>
              )}
            </GlassCard>
          ))}
        </div>
      )}
    </div>
  );
};
